file: "net-scan.hosts"
scan:
  ports: [22, 80, 443]
  port-range: "10-11"
  network: "tcp"
  timeout: 1000
  filter-state: ""
ping:
  timeout: 10s
  interval: 1s
  count: 0
  size: 56
  ttl: 64
  iface: ""
  tclass: -1
  privileged: true
http:
  call-frequency: 1s
  timeout: 5s
  secure: true
